In [1]:
import numpy as np

In [5]:
a=np.zeros(10)

In [6]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
b=np.zeros(shape=(3,5))

In [12]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
c=np.zeros(shape=(12,1))

In [20]:
c

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
e=np.array([[1,1,1,1,1]])
f=np.array([[2],[2],[2],[2],[2]])
g=np.dot(f,e)
g

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])