In [3]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]='2'

In [4]:
import tensorflow as tf

In [8]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [9]:
y=tf.constant([[1,2,3],[4,5,6]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [10]:
z=tf.ones((3,5))
z

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
a=tf.eye(6,6)
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [23]:
b=tf.random.normal((6,6),mean=0,stddev=10)
b

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[ -4.7481337,  12.210878 ,  -2.0023086, -21.3004   ,   4.5885267,
          3.806322 ],
       [ 21.41668  ,   8.456155 ,   7.111986 ,   2.5679219,   6.376887 ,
          1.4963486],
       [ 29.065338 ,   8.497323 ,  10.643522 , -12.82695  ,  -8.04072  ,
          1.9150934],
       [  2.953882 ,  -3.1944263,  -4.634528 ,  -3.5760107,  22.338095 ,
         -2.9712434],
       [ 12.185359 ,   9.833058 ,  -4.575215 ,  -4.4883223,   7.6799397,
         -3.8823895],
       [  6.237595 ,  15.768495 , -12.055788 ,   5.1071386, -11.800784 ,
         17.706558 ]], dtype=float32)>

In [25]:
c=tf.random.uniform((6,6),minval=0,maxval=100)
c

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[42.126083  , 18.55452   , 94.92043   , 50.314556  , 95.80733   ,
        88.254944  ],
       [68.69467   ,  0.42922497, 49.44568   , 96.35692   , 93.41554   ,
        48.06223   ],
       [ 1.6431212 , 18.277096  , 47.868824  , 19.942295  , 85.35114   ,
        45.22365   ],
       [91.58202   ,  5.7005286 , 89.83343   , 42.37331   , 33.44388   ,
        71.52502   ],
       [57.178318  , 41.94212   , 43.58121   , 34.149326  ,  3.0951262 ,
        31.777239  ],
       [57.670116  , 19.112228  , 22.336758  ,  6.062329  , 63.99075   ,
         6.22983   ]], dtype=float32)>

In [30]:
d=tf.range(start=1,limit=20,delta=3)
d

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19], dtype=int32)>

In [31]:
d=tf.cast(d,dtype=tf.float64)
d

<tf.Tensor: shape=(7,), dtype=float64, numpy=array([ 1.,  4.,  7., 10., 13., 16., 19.])>

In [50]:
e=tf.constant([1,2,3])
f=tf.constant([4,5,6])
g=tf.divide(e,f)
g
# e+f

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [51]:
h=tf.tensordot(e,f,axes=1)
h

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [54]:
g**0.00001

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.99998614, 0.99999084, 0.99999307])>

In [59]:
i=tf.random.normal((6,6))
j=tf.random.normal((6,6))
z=tf.matmul(i,j)
z

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[-1.3364303 , -2.0092046 ,  1.7626667 , -0.79861915,  0.42268172,
        -0.31710047],
       [-1.0628395 , -3.6026402 ,  4.3347487 , -1.6894269 ,  1.7727787 ,
        -0.8869183 ],
       [-1.3834059 , -0.46634263,  0.31644946,  0.53023696, -0.40930927,
         0.5267836 ],
       [ 3.499051  ,  1.5334473 , -2.1442704 ,  1.3864776 ,  1.8463405 ,
        -1.4725478 ],
       [ 0.2613932 ,  2.7696853 , -4.718725  , -1.9446223 , -2.3725514 ,
         0.07740372],
       [ 1.921792  , -0.34836125, -1.0156876 ,  0.8120877 ,  1.4544367 ,
        -2.135289  ]], dtype=float32)>

In [60]:
k=tf.range(11)
k

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [68]:
k[::-1]

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0], dtype=int32)>

In [69]:
indices=tf.constant([0,3])
x_ind=tf.gather(k,indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

In [80]:
x=tf.constant([[1,2],[ 3,4],[5,6]])
x[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [79]:
x=tf.reshape(x,shape=(6,1))
x

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [83]:
x=tf.transpose(x)
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>